language: node_js
node_js:
  - "6.10"
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
  - wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
  - java -jar selenium-server-standalone-3.4.0.jar -port 4444 > /dev/null &
  - sleep 5
  - node src/server/index.js > /dev/null &
  - sleep 5
