sudo: required
language: node_js
dist: trusty
node_js:
- '6.10'
script: yarn test
deploy:
  provider: heroku
  api_key:
    secure: C5AzVqq52/FdYDVGCA+Y3Tn8fUVc9eOdoxlJEeSKPCm3Phxo0A0q8gtvaOCUGzd2I9Rmkzda9RUq5BcoT6UnTaPXs6F9EPVF1VXxV9Se3o8Um2wzT1RtJlPfAmSKAsfyVQIgjdHSiONBWsXb4qMlIPWXGBDdGLhvGDR/3ON4suCIWP2qS2NBkVCUU1/xpkdAp2wmUlq7hmyFBueL43QR9Dnj9kOXTJsGCh+mV/4Lb4JuM/OGAOpjbXccp2P+nmL08XwzDDhRwbFrSS1/6F7N7iJKy0C9xAo3nKBn9adVuXMMrLiEIB0IW5/7PYNgFuoo9LqMuk/EE8l8/7Wnh4quVRwBAVUnNDW6QG7qK5ageTUnNqWWNPLMCAR9OVPGEdmCRtp02R/wyVlMiltGEX/hjM+8PtfTfjA8MkN60Z9Cx1OuPzNzAub3p/9vSVwi3laeUxTMAGsxJ9eE4voyN2oELoFeLd3lVxyXW+V8Xbq6NGUwbSPIbPozWbdbcpybvUMsTfMge5xjaJDNiP/HUZiIFj1FZQSDY7NjBYVw8YUmhVD9cWv6X61RU3HLP/yzEHtKqy/IWTDLcY7pGW0YvsSxjN35KE1vc+MR0JUUjmEDMRLsSFq0ugPenP9Kb6d7u1IcVqdbMOlRWbooQgZOJGm9TmlgKgi9dt4tdk4vx+stXyM=
  app: rocky-chamber-96353
