sudo: required
language: node_js
dist: trusty
node_js:
  - "6.10"
script: yarn test
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
  - wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
  - wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - java -jar selenium-server-standalone-3.4.0.jar -port 4444 > /dev/null &
  - sleep 5
  - node src/server/index.js > /dev/null &
  - sleep 5
