sudo: required
language: node_js
dist: trusty
node_js:
  - "6.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
  - java -jar selenium-server-standalone-3.4.0.jar -port 4444 > /dev/null &
  - node src/server/index.js > /dev/null &
  - sleep 5
